### ISSUE TITLE
ERB Protocol specification v0.1.0

### ISSUE THREAD

**Issue by pfried** [emlid/reachrs-docs#197]
Concerning the [ERB Protocol Specifciation](https://files.emlid.com/ERB.pdf)

The packet structure graphic shows the 2 sync chars as 1 = "R" and 2 = "E" which is the wrong order imho. Apart from that the order seems to be correct in the following descriptions.

![image](https://user-images.githubusercontent.com/1744875/74157494-a89cdd00-4c18-11ea-8b7e-5265f30ea25a.png)

**Comment by ArtemFomenko** [comment]
Hi @pfried,

Thank you for noting that typo! We've fixed the link to the ERB protocol description [in our guide on ArduPilot integration.](https://docs.emlid.com/reachm2/ardupilot-integration/)
