### ISSUE TITLE
edge: New recommended repo for rtl8812au

### ISSUE THREAD

**Issue by lucasdemarchi** [emlid/reachrs-docs#214]
It was always a pain for me not having the rtl8812au as an upstream kernel module. Fortunately at least now there is a fork that is maintained much closer to upstream. I just installed it for 5.5.5 and it's working fine:

https://github.com/gnab/rtl8812au

It would be nice to get the quickstart page updated with this info.

**Comment by ArtemFomenko** [comment]
Hi @lucasdemarchi,

The Aircrack-ng's rtl8812au driver for Linux repo is a more active one. It is still developing and the driver at 5.3.4 stable branch supports kernel version 5.4. The 5.6.4.2 default branch is in progress and git users still commit to it. 

Additionally, an Aircrack-ng repo looks trustworthy as they continuously make and support network software.
