### ISSUE TITLE
Recommend the default navio image

### ISSUE THREAD

**Issue by acxz** [emlid/reachrs-docs#231]
I tried to use the recommended image by the documentation here https://github.com/emlid/emlid-docs/blob/master/docs/autopilots/common/ardupilot/configuring-raspberry-pi.md, however ran into the following issue: https://github.com/emlid/pi-gen-navio/issues/4

Looking a bit deeper, `navio-stretch` is the default branch not `navio-buster`, I believe the `navio-buster` link has been updated to the documentation prematurely. Should the link be changed back to the stable and working `navio-stretch` one, instead of `navio-buster`? At least until the `navio-buster` branch is the default one for generating the navio image?

**Comment by ArtemFomenko** [comment]
Hi @acxz,

Thank you for your request. We will test your PRs soon.

**Comment by acxz** [comment]
@ArtemFomenko in the meanwhile while you guys test the PRs and fix the issues, should the link be changed back to the stable and working `navio-stretch` one?

If you could answer my question directly that would be appreciated instead of skirting around them.

Thank you

**Comment by acxz** [comment]
Closing as the link has been properly fixed
