### ISSUE TITLE
Error in build instructions

### ISSUE THREAD

**Issue by q-wertz** [emlid/reachrs-docs#286]
The order of commands for building Ardupilot is wrong 
(see: https://github.com/ArduPilot/ardupilot/issues/14526)

Didn't make a pull request as it maybe should also be changed in the other descriptions (Copter etc.)

**Comment by ArtemFomenko** [comment]
Hi @q-wertz,

Thanks for noticing it.

We'll reproduce the issue and come back with the feedback.

**Comment by ArtemFomenko** [comment]
Hi @q-wertz,

Thank you for your report. We've updated [the corresponding article](https://docs.emlid.com/navio2/common/ardupilot/building-from-sources/#building-ardupilot-using-waf-build-system). The same behavior was observable with ArduCopter, that is why the doc required reworking.
