### ISSUE TITLE
Missing antenna phase center information RS2

### ISSUE THREAD

**Issue by q-wertz** [emlid/reachrs-docs#290]
I didn't find any information to the Antenna Phase Center offsets in the docs for the RS2 receiver. 
Only in the forum someone mentioned it https://community.emlid.com/t/rs2-question-measure-point-to-apc/17233

Would be nice to have this information also in the documentation (from an official source) somehow like for the M2 receiver https://docs.emlid.com/reachm2/specs/

**Comment by ArtemFomenko** [comment]
Hi @q-wertz,

Thank you for your suggestion. We will consider adding this info to the specs page.

In the meantime, the info on the Antenna Phase Center of RS2 is available [on the general drawings page](http://files.emlid.com/docs/reachrs2-drawing.pdf) in specs.

**Comment by ArtemFomenko** [comment]
Hi @q-wertz,

We've added the info on antenna height for [Reach RS+](https://docs.emlid.com/reachrs/specs/#electrical-specs) and [Reach RS2](https://docs.emlid.com/reachrs2/specs/#electrical-specs) to our docs.
