### ISSUE TITLE
Navio2: Document the location of log files

### ISSUE THREAD

**Issue by jratike80** [emlid/reachrs-docs#341]
It seems to be a common problem that downloading DataFlash logs through Mavlink may be very slow. Thanks to this forum topic https://community.emlid.com/t/can-download-dataflash-log-but-cant-find-on-sd-card/13803/5 I could download the log files directly from Raspberry in seconds with WinSCP. 
```
Please check the /var/lib/ardupilot/logs folder.
You should look for .BIN files, not .bin.
```
I am not sure where in the documentation would be the best place for that valuable piece of information.

**Comment by liudmilaslepova** [comment]
Hi @jratike80,

Thanks for the suggestion! 

We’ll consider the possibility of adding this information.
