### ISSUE TITLE
Wrong description of Ardupilot integration

### ISSUE THREAD

**Issue by q-wertz** [emlid/reachrs-docs#355]
In the description of the Ardupilot integration of [Reach M2](https://docs.emlid.com/reachm2/ardupilot-integration/) and [Reach M+](https://docs.emlid.com/reachm-plus/ardupilot-integration/) it is stated, that:

> Then set SERIAL4_PROTOCOL parameter to "20" - NMEA Output. This will enable Serial4 port to be used as NMEA output.

(The statement itself is correct but at this point you don't want that. You want the Ardupilot to know that there is a GPS attached and it can use it as an NMEA **Input**)

I tried a lot but for me it only works when setting it to "5" - GPS.

In my opinion this is an error in the description.

Mission Planner: 1.3.74
Ardupilot: ardurover-4.0

**Comment by liudmilaslepova** [comment]
Hi @q-wertz,

These parameters should work with no issues when you set all the other options according to the guide. We have thoroughly tested this setup and reworked the guide recently. Please check that you choose NMEA as position output on the Reach device and set the GPS_TYPE2 parameter to 5. 

If this doesn't help, please create a new thread on the community forum so we could proceed the further troubleshooting with you.

**Comment by q-wertz** [comment]
See https://community.emlid.com/t/ardupilot-integration-rtk/22250
